Repository tulibraries/cob_datapipeline, pull requests merged in 2019-04, with the labels that each got.

#29 Bl 841 reindex skip supressed
  almaoai_harvest.py
  almasftp_fetch.py
  processtrajectlog.py
  scripts/ingest_marc.sh
  scripts/ingest_marc_multi.sh
  task_ingestmarc.py
  task_ingestsftpmarc.py
  tul_cob_fullreindex_dag.py
  tul_cob_pipeline_dag.py
Labels: review

#26 merging changes from deploy-prep pr
  README.md
Labels: airflow-qa

#25 Assume rbenv is installed.
  scripts/ingest_marc.sh
  scripts/ingest_marc_multi.sh
Labels: airflow-qa, review

#33 Deploy QA via qa branch & ansible in travis
  .travis.yml
  .travis/deploy.sh
Labels: review

#34 trying to get deploy step to run
  .travis.yml
  .travis/deploy-master.sh
  .travis/deploy-qa.sh
  README.md
Labels: review

#35 trying to get travis to see devops user ssh key
  .travis/deploy-qa.sh
Labels: review

#36 debug attempt at travis ssh env
  .travis/deploy-qa.sh
Labels: review

#37 debug attempt at travis ssh env
  .travis/deploy-qa.sh
Labels: review

#38 Set up qa deploy
  .gitignore
  .travis.yml
  .travis/.conan_the_deployer.enc
  .travis/.gritty_travis.enc
  .travis/deploy-master.sh
  .travis/deploy-qa.sh
Labels: review

#39 travis can only take 1 encrypted file
  .gitignore
  .travis.yml
  .travis/.conan_the_deployer.enc
  .travis/.gritty_travis.enc
  .travis/deploy.zip.enc
Labels: review

#40 remove mkdir for .ssh folder that already exists
  .travis.yml
Labels: review

#41 updating ssh git clone urls
  .travis/deploy-master.sh
  .travis/deploy-qa.sh
Labels: review

#42 silly indentation update to trigger travis
  .travis.yml
Labels: review

#44 fixing ansible-playbook command for private-key
  .travis/deploy-master.sh
  .travis/deploy-qa.sh
Labels: review

#46 adding verbose output to ansible build wihtin travis
  .travis/deploy-qa.sh
Labels: review

#47 adding travis deployment script for deploy job
  .travis/deploy-qa.sh
Labels: review

#48 removing EOF from deploy bash script
  .travis.yml
  .travis/deploy-qa.sh
Labels: review

#53 Fix sftp logging, create data dir if not exist
  almasftp_fetch.py
Labels: review

#55 Fix ingest rubies
  scripts/ingest_marc.sh
  scripts/ingest_marc_multi.sh
Labels: review
